### ISSUE TITLE
Externalize the viewport settings

### ISSUE THREAD

**Issue by Damianofds** [slms4redd/slms-geo-portal#1]
The initail extent is hardcoded in the portal js core files.
The old portal used a static file called **custom.js** for this kind of configurations.
Implement something like the old behaviour: a js file where the basic settings are managed

**Comment by sgiaccio** [comment]
Config parameters are now in assets/config.json. Needs a rebuild after changes.

**Comment by Damianofds** [comment]
Ciao Stefano, a couple of questions:

- Is it possible to move this config file in **static** directory in order to avoid to rebuild the app?
- Is it possible to EXTERNALIZE the whole **static** directory?
- Is the OpenLayers **restricted extent** property supported? I would avoid to zoom and pan out of the country

**Comment by sgiaccio** [comment]
Ciao Damiano,

Yes it's possible to move the config file in the static directory, I haven't done it yet to reduce the number of http requests. We could maybe put the configuration parameters in layers.json?

The static directory is not included in the build, it can be moved as long as it's accessible with the same url (/static).

The restricted extent is not supported yet, I'll add a new issue for it.
